version: '2'
services:
  influxdb:
    image: influxdb:1.1.1
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb/data
  sample-influxdb-worker:
    build: .
    environment:
      INFLUX_URL: http://influxdb:8086/tweets
      TWITTER_CONSUMER_KEY: 
      TWITTER_CONSUMER_SECRET: 
      TWITTER_ACCESS_TOKEN: 
      TWITTER_ACCESS_SECRET: 
    links:
      - influxdb
    command: reflex -r '\.go$$' -s -- sh -c 'go build && ./sample-influxdb -worker'
  sample-influxdb:
    build: .
    ports:
      - 3000:3000
    environment:
      INFLUX_URL: http://influxdb:8086/tweets
    links:
      - influxdb
    command: reflex -r '\.go$$' -s -- sh -c 'go build && ./sample-influxdb'


